<?php
//
// Load the payex online object
//
$standard = Mage::getModel('payex/standard');

if (Mage::registry('payment_error') != "") {
?>
<h1><?php echo $this->__('PAYEX_LABEL_1'); ?></h1>
<table border="0"><tr><td align="right" valign="top">
<a href="http://www.payex.com" border ="0" target="_blank"><img src="<?php echo $this->getSkinUrl('images/payex/payex_logo.gif'); ?>" border ="0"></a>&nbsp;&nbsp;
</td><td align="left" valign="top">
<img src="<?php echo $this->getSkinUrl('images/i_msg-error.gif'); ?>" alt="Error">
<?php 
echo $this->__('PAYEX_LABEL_5') . '<br />';

if (Mage::registry('payment_error') == "bank") {
	echo Mage::registry('code');
	echo '<br />';
	echo Mage::registry('desc');
}
else if (Mage::registry('payment_error') == "thirdparty")
	echo Mage::registry('code');

echo '<br /><br /><a href="' . $this->getUrl('checkout') . '">';
echo $this->__('PAYEX_LABEL_6'); 
echo '</a>';
?>
</td></tr></table>
</div>
<?php
}

?>
