<?php

?>
<fieldset class="form-list">
    <?php $_code=$this->getMethodCode()	?>
	
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>											
            <?php echo $this->__('PAYEX_LABEL_2'); ?>
			&nbsp;<a href="<?php echo $this->__('PAYEX_LABEL_13'); ?>" target="_blank" style="text-decoration: underline; font-weight: bold;"><?php echo $this->__('PAYEX_LABEL_14'); ?></a>
        </li>
		</ul>
</fieldset>